### ISSUE TITLE
Problem  with setup of Bassa Mobile

### ISSUE THREAD

**Issue by somenath1435** [scorelab/Bassa-mobile#52]
@gayashanbc 
I'm facing problem while setting up the project
The command "python3 setup.py develop" is giving error:

![Screenshot from 2020-01-31 10-27-40](https://user-images.githubusercontent.com/43093724/73499667-bb2c4080-43e6-11ea-9f69-8fbb85550800.png)

Mysql is corrrectly setup on ubuntu18 already
Thanks

**Comment by JaDogg** [comment]
Ensure you have mysql_command? It would be easier to try Docker compose
